spring.application.name=banking_system
server.port=8085

# mybatis
mybatis.mapper-locations=classpath:mapper/mybatis/**/*.xml

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//192.168.0.127/testdb
spring.datasource.username=banking
spring.datasource.password=1234

#jwt
jwt.secret=sorkaksdlfgksmfdlfkasusrmeodnloa
jwt.expiration=60000

# root(프로젝트 전체)의 로그 레벨을 DEBUG로 설정
logging.level.root=info
logging.level.com.example.demo=debug