spring.application.name=banking_system

# HTTPS 포트 설정
server.port=8443

# SSL 설정 활성화
server.ssl.enabled=true

# 사용할 키스토어 타입 (PKCS12)
server.ssl.key-store-type=PKCS12

# 키스토어 파일 위치 (classpath: 주소는 src/main/resources)
server.ssl.key-store=classpath:keystore.p12

server.ssl.key-store-password=1234

# 별칭 (명령어에 넣었던 -name 값)
server.ssl.key-alias=tomcat

# mybatis
mybatis.mapper-locations=classpath:mapper/mybatis/**/*.xml

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//192.168.0.127:1521/testdb
spring.datasource.username=banking
spring.datasource.password=1234

#jwt
jwt.secret=sorkaksdlfgksmfdlfkasusrmeodnloa
jwt.expiration=1800000

# root(íë¡ì í¸ ì ì²´)ì ë¡ê·¸ ë ë²¨ì DEBUGë¡ ì¤ì 
logging.level.root=info
logging.level.com.example.demo=debug

# enable cache
spring.cache.type=redis

# 파일 경로
file.upload-dir=/Users/dalongiyam/bnk-upload/
file.max-size=10MB
file.allowed-type=pdf

